### ISSUE TITLE
VAB Log Spam ModuleLifeSupport 1.1.0.1228

### ISSUE THREAD

**Issue by CraveMode** [BobPalmer/USI-LS#105]
KSP: 1.1.0.1228/1224/1215/1209
USI-LS: 0.4.1.0

With a fresh version of KSP 1.1.0.1228 and all of the USI mods from CKAN with author of Roverdude, I am getting the log spam below. This starts when in the VAB when loading a part or a ship from the stock ships or my own. It stops when you leave the VAB but starts up when you create a root part.

`ERROR Object reference not set to an instance of an object IN ModuleLifeSupport`

[output_log.txt](https://github.com/BobPalmer/USI-LS/files/226124/output_log.txt)

Update: This also does the same thing for previous KSP versions all the way back to 1209 with USILS installed with other USI Mods.

**Comment by BobPalmer** [comment]
Fixed in next patch
