### ISSUE TITLE
UKS Recycler State Not Persistent

### ISSUE THREAD

**Issue by EnDSchultz** [BobPalmer/USI-LS#111]
Reported this in the USI Kolonization thread. When loading a Kolonization module I had left with Life Support active, the tooltip shows it as "inactive" and I have to cycle the Life Support button (Stop, then Start) to get it to turn on again. This affects all the UKS modules with a Life Support toggle that I've tried thus far.

KSP 1.1.2
UKS 0.40.2.1
USI-LS 0.4.2.1.

![screenshot6](https://cloud.githubusercontent.com/assets/18756535/14938944/d122fd9c-0ee9-11e6-80da-8c46bd5bb7ef.png)
![screenshot7](https://cloud.githubusercontent.com/assets/18756535/14938943/d12235b0-0ee9-11e6-81d6-0da838ad2b59.png)
![screenshot8](https://cloud.githubusercontent.com/assets/18756535/14938945/d125f59c-0ee9-11e6-8a3a-7c551df64ad0.png)

**Comment by BobPalmer** [comment]
Should be sorted
