### ISSUE TITLE
24h time causes inconsistent values

### ISSUE THREAD

**Issue by drazed** [BobPalmer/USI-LS#112]
Calculated supplies/day time-remaining inconsistent when using Earth Time (24h days, 365d years).

4 photo's attached, one showing LS dialog with standard kerbal time and one with Earth Time (this is enable in 'General' settings before starting/opening a saved game).  Additionally 2 photos of the General settings showing Kerbin/Earth time setting.

Discovered this specifically due to using RSS, but RSS is not required for the kerbin/earth time setting, thus this does affect stock (non-RSS) if someone chose to use Earth Time in a stock game.

First image shows Earth Time (the actual bug), this shows:
- 799 supplies (48.6/day)
- 4d:02h:41m:26s time reamining, with 3 crew present

Second image shows Kerbin Time (default), this shows:
- 799 suplies (48.6/day)
- 16d:02h:41m:08s

The other two images just show the specific setting, which is only available in the main settings area BEFORE starting a game.

If Earth Time is selected, either the supplies/day should be 4X more, or the time remaining should be 4X more.

Tested on stock ksp v1.1.2 with just USI life-support v0.4.2.1 and dependencies.

GameData content:

```
$ ls -1
000_USITools
CommunityResourcePack
ModuleManager.2.6.24.dll
Squad
UmbraSpaceIndustries
```

![screenshot0](https://cloud.githubusercontent.com/assets/2659/14939556/f1b8d574-0f00-11e6-8633-cb699d7dec9f.png)
![screenshot1](https://cloud.githubusercontent.com/assets/2659/14939557/f41c89aa-0f00-11e6-9106-241acbd41316.png)
![screenshot2](https://cloud.githubusercontent.com/assets/2659/14939558/f64985ac-0f00-11e6-9921-b3616a002ab7.png)
![screenshot3](https://cloud.githubusercontent.com/assets/2659/14939559/f821dfdc-0f00-11e6-88bb-06bb7ef1d7d0.png)

**Comment by Kerbas-ad-astra** [comment]
The consumption number should increase, since the "day" is longer. (I added the code to fix the displayed duration, but I see I forgot to fix the displayed rate.)
