### ISSUE TITLE
Notification spams when Hab Timer is up

### ISSUE THREAD

**Issue by tand00ri** [BobPalmer/USI-LS#114]
[Kerbin Dallas Multipass.zip](https://github.com/BobPalmer/USI-LS/files/247955/Kerbin.Dallas.Multipass.zip)
See the attached save file, as well as imgur gallery and notes for more information - when the hab timer runs out, getting constant UI spam. removed most mods, except those that are commonly used (KER, KJR, KAC, Chatterer, ContractConfigurator, PreciseNode, Trajectories, Scatterer, Coherent Contracts, [X]Science, etc.) . Saved and reloaded game, issue persists.

Screenshot album (before, just before, after):

http://imgur.com/a/Yjrdy

Current Settings:

Let me know if you need any more information - thanks!

LIFE_SUPPORT_SETTINGS
{
	SupplyTime = 324000			//How many seconds before Kerbals are affected by no supplies
	EVATime = 21600				//How many seconds before ill effects on EVA
	ECAmount = 0.01				//EC per Kerbal per second						
	SupplyAmount = 0.00075		//Supplies consumed per Kerbal per second
	WasteAmount = 0.00075		//Mulch produced per Kerbal per second
	NoSupplyEffect = 1			//Effect if a Kerbal has no supplies or EC
	NoSupplyEffectVets = 1		//Effect if a Kerbal is a vet and has no supplies or EC
	EVAEffect = 1				//Effect if a Kerbal exceeds EVA time		
	EVAEffectVets = 1			//Effect if a Kerbal is a vet and exceeds EVA time
	NoHomeEffect = 0			//Effect if a Kerbal becomes homesick
	NoHomeEffectVets = 0		//Effect if a Kerbal is a vet and becomes homesick
	HabMultiplier = 5			//Bonus to hab values (1 = default = 100% of the part's rated value)
	HomeWorldAltitude = 25000	//Altitude on Kerbin that negative effects are removed
	BaseHabTime = 1				//How long can 1 crew capacity support 1 Kerbal, expressed in Kerbal Months
	ReplacementPartAmount = 0	//How fast life support equipment and habs 'wears out'
	HabRange = 150				//How close we need to be to use other vessel's habitation modules and recyclers.
	EnableRecyclers = true		//Use resource recyclers?  Not the same as resource converteres like greenhouses!
	VetNames = Jebediah,Valentina,Bill,Bob	
}

**Comment by BobPalmer** [comment]
Thank you!

**Comment by BobPalmer** [comment]
Fixed
