### ISSUE TITLE
Supplies duration in VAB not updated when recyclers added

### ISSUE THREAD

**Issue by MarkSRobinson** [BobPalmer/USI-LS#118]
If you create a vessel with crew and supplies (Ex: Mk2 Lander Can and Life Support Tank) and you get a Supplies for 2 value of 138 days in the Life Support Status window.

If you attach a UKS Pioneer Model (Orbital), it will show a recycler of 75%, and increase the Habitation time to 60 days.  It will not change the Supplies value, when it really should.  Without this, it makes planning a long duration mission much harder

**Comment by BobPalmer** [comment]
Working now
