### ISSUE TITLE
Adjust Mutinous Behavior

### ISSUE THREAD

**Issue by BobPalmer** [BobPalmer/USI-LS#120]
...to generate a token amount of supplies to stop cascading mutiny

**Comment by DanStaal** [comment]
I don't know.  Having one Kerbal go crazy sounds like something that should drive the others closer to the brink...
(Not that I play with anything set to mutiny.  I tend to believe my Kerbals are a bit smarter than to start ripping up the machines keeping them alive.)

**Comment by BobPalmer** [comment]
Fixed next patch
