### ISSUE TITLE
Rescue contract kerbal stuck as Tourist

### ISSUE THREAD

**Issue by KevinMilcz** [BobPalmer/USI-LS#125]
I got a rescue contract where the kerbal was stuck in a mk v workshop. The kerbal was transformed into a Tourist because the workshop has no hab rating. When I got him back to KSC, he was still a tourist.

I understand we can't fix random parts getting put into rescue contracts from BobPalmer/MKS#679 but is there maybe a missing hook for ship recovery to revert upset kerbals back to their normal type?

**Comment by BobPalmer** [comment]
If they do not return to their normal state after landing, simply re-launch the Kerbal in a new vessel and this will force a reset
