### ISSUE TITLE
Supply resource missing -UPDATED-

### ISSUE THREAD

**Issue by Worm61** [BobPalmer/USI-LS#127]
A while ago, I made this issue post:

"I recently started playing KSP again after a long time away. I've been away for a few updates, so today I reinstalled all my USI mods. Now when I add life support tanks to my ships, they still show as having no supplies on the Life Support menu. I thought maybe the containers defaulted as empty, so I tried to fill them in the SPH, but I couldn't open up the menu. I right-click on the tank and nothing happens. This is happening with every life support container I've tried. The effects of the mod continue to work, so the Kerbals act as if they have no supplies, and the countdown to mutiny starts."

Since making the post, I have noticed a number of other resources missing as well. Just today, there was a single line reply, "Bad install, you are missing CRP." and the issue was immediately closed, with no request for further details, and giving me no chance to respond.

The problem with this reply is that I have installed and reinstalled both Life Support and the separate Resource Pack at least three times each, and the resources are missing each and every time. I have gone through the folders, and the resource pack is present and contains some, but not all, resources. So if it's a bad install, how exactly am I supposed to get a good install when it's bad every single time?

**Comment by BobPalmer** [comment]
Then there is something not being provided in the info above, given how many people install this mod.  your best bet is to head to the forums, post the issue there, so more folks can help out analyzing the install issue.
