### ISSUE TITLE
VAB/SPH life support status window adds to readouts when removing parts

### ISSUE THREAD

**Issue by JoelPreuss** [BobPalmer/USI-LS#137]
When placing a part in the VAB/SPH, the life support status window adds the total amount of resources in the current vessel to the totals in the window. This happens even when a part not attached to the current vessel but still in the scene is picked up. The totals will gradually increase, leading to two part ships with over 600 crew and years worth of ElectricCharge. Habitation timers and calculations are also affected. Values will persist until the player exits the VAB/SPH.

The per-part breakdown section is unaffected and functions as normal.

This does not impact the vessel's actual habitation times. In flight the status window will display correct values.

This issue manifests was observed with USI Life Support v0.5.2.0 with no other mods (besides Module Manager) installed. It was also observed with the full constellation installed as well. 

![screenshot10](https://cloud.githubusercontent.com/assets/7650768/19414809/409762bc-931f-11e6-98da-091272a4426b.png)

**Comment by GHRyanK** [comment]
Can confirm similar behavior.  In VAB, life support stats will either be blank, or will incrementally and non-reversibly add up when parts are added or removed, but will revert to expected values on launch pad.  Also briefly observed this behavior during ongoing mission: hab time did not expend while on launch pad, but started counting after launch, then temporarily doubled when two-stage vehicle separated in flight, then reverted to correct values after about 2-3 seconds.

On a related note, can Colony Supplies be used to extend Hab Time without a dedicated Colony Supplies consumer module?  Was curious to see if I could extend Hab time of basic crewed command pod without adding additional habitable modules.  Tried adding a Mk V Redi-Pak filled with Colony Supplies to see if crew would consume them, but no joy....

**Comment by JoelPreuss** [comment]
Confirming that v0.5.3.0 fixes this issue. I'm also seeing confirmation on the forums as well, so I think it's safe to say this is fixed. Thank you RoverDude!

@GHRyanK, I think the MKS thread on the forums would be a better place for gameplay-related questions. If nothing else, there's more eyes there, and RoverDude is very active there.
