### ISSUE TITLE
Missing NomTank_N texture?

### ISSUE THREAD

**Issue by puetzk** [BobPalmer/USI-LS#142]
```
[LOG 08:46:31.526] Load(Model): UmbraSpaceIndustries/LifeSupport/Assets/Tank_125
[ERR 08:46:31.530] Texture 'UmbraSpaceIndustries/LifeSupport/Assets/NomTank_N' not found!

[LOG 08:46:31.534] Load(Model): UmbraSpaceIndustries/LifeSupport/Assets/Tank_250
[ERR 08:46:31.538] Texture 'UmbraSpaceIndustries/LifeSupport/Assets/NomTank_N' not found!

[LOG 08:46:31.540] Load(Model): UmbraSpaceIndustries/LifeSupport/Assets/Tank_375
[ERR 08:46:31.544] Texture 'UmbraSpaceIndustries/LifeSupport/Assets/NomTank_N' not found!
```

Looks like this used to exist (I found it at https://github.com/BobPalmer/USI-LS/blob/f3c5bfd852a171b36953612c3fe418aa2595ed3c/FOR_RELEASE/GameData/UmbraSpaceIndustries/LifeSupport/Assets/NomTank_N.dds).

Looks somewhat similar to NomTank_N_NRM.dds that is now included and used by the Fertilzer tanks, but they used to both exist and be separate back in BobPalmer/USI-LS@f3c5bfd852a171b36953612c3fe418aa2595ed3c

**Comment by BobPalmer** [comment]
Fixed
