### ISSUE TITLE
Time remaining displayed incorrectly when on earth time. Also feature request: More displayed information.

### ISSUE THREAD

**Issue by Marcafk** [BobPalmer/USI-LS#15]
When running in earth time the time remaining is still divided into 6 hour days, for instance incorrectly reporting 90 days remaining instead of 15 when having a single kerbal with a minipack.
Also a feature request, could the time remaining also be modified to take into account supplies production, or have displays underneath showing consumption, production ,balance and adjusted time remaining?
 I notice that when turning on a pioneer module or greenhouse that time remaining stays at 90 days based on total stored supplies, rather than halving based on apparent balance.

**Comment by BobPalmer** [comment]
Should be corrected
