### ISSUE TITLE
Hab Time and Hab Multipliers double counting or otherwise not working as expected

### ISSUE THREAD

**Issue by tarheel1999** [BobPalmer/USI-LS#150]
These issues primarily concern lines 264-297 in LifeSupportManager.cs. 

Issues:
- When multiple vessels are within hab range the hab time for the active vessel is being double counted.  
- Hab multipliers are non-intuitive with multiple crew and multiple hab multipliers.
- Hab multipliers work differently depending on whether hab parts are part of one vessel or two.

Examples:

`1.` 

**Same Vessel** -  One Kerbal, two Mk1 pods, and two small cupolas. In this vessel there are 4 hab months and two parts with a .5 HabMultiplier with a crew capacity of 1 kerbal. This produces:
- No habs active
  - 30 days of hab time (7.5 x 4)
- 1 hab active
  - 45 days of hab time (7.5 x 4 x 1.5)
- 2 habs active
  - 60 days of hab time (7.5 x 4 x 2)

**Separate Vessels** - One Kerbal, one Mk1 pod, and one small cupola within the hab range of a vessel with one Mk1 pod and one small cupola. Each vessel has 2 hab months and one part with with a .5 HabMultiplier with a crew capacity of 1 kerbal. This produces:
- No habs active
  - 45 days of hab time (7.5 x _**6**_ ). 
- 1 hab active 
  - 67.5 days of hab time (7.5 x _**6**_ x 1.5)
- 2 habs active 
  - 90 days of hab time (7.5 x _**6**_ x 2)

In all three of the above scenarios the active vessel's hab/crew space is double counted because the method first collects the hab time of the active vessel and then loops through all the vessels within the hab range and includes the active vessel).

`2.` 

**Same Vessel** - Two Kerbals, two Mk1 pods, and two small cupolas. In this vessel there are 4 hab months and two parts with a .5 HabMultiplier with a crew capacity of 1 kerbal. This produces:
- No habs active
  - 15 days of hab time per Kerbal (7.5 x 4)
- 1 hab active
  - 18.75 days of hab time per Kerbal  (7.5 x 4 x 1.25)
- 2 habs active
  - 22.5 days of hab time per Kerbal  (7.5 x 4 x  _**1.5**_)

I understand the multiplier of 1.25 when only one of the habitats is activated as the small cupola only has a crew capacity of 1. I find it unintuitive that the multiplier is 1.5 when both habitats are active.   Between the two small cupolas there is a total crew capacity of two. The hab bonus should not be reduced here as the cupolas are not overcapacity/overstuffed, i.e., there is one cupola for each kerbal.

**Separate Vessels** - One Kerbal, one Mk1 pod, and one small cupola within the hab range of a vessel with one Kerbal, one Mk1 pod, and one small cupola. Each vessel has 2 hab months and one part with with a .5 HabMultiplier with a crew capacity of 1 kerbal. This produces:
- No habs active
  - 22.5 days of hab time for each Kerbal (7.5 x _**6**_)
- 1 hab active
  -  Vessel with active hab -  33.75 days of hab   (7.5 x _**6**_ x  _**1.5**_)/2
  -  Vessel without multiplier -  28.125 days of hab  (7.5 x _**6**_ x _**1.25**_)/2
- 2 habs active
  -  Each vessel - 39.75 days of hab time per Kerbal  (7.5 x _**6**_ x _**1.75**_)/2

Here you see that the hab time is double counted for the active vessel which results in 6 hab months instead of 4. You can also see that the hab multipliers are flat out wonky here. With one hab active, the  vessel with the multiplier receive the full hab bonus (1.5) while the other vessel receives half of the bonus (1.25). They both should only receive 1.25.  With both habs active both vessels receive their full hab bonus plus half of other vessel's hab bonus (1 + .5 + .25). They both should only receive 1.5.

**Comment by BobPalmer** [comment]
Sorted :)  will be in next patch
