### ISSUE TITLE
Category typo for several parts

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/USI-LS#155]
Most USI-LS parts have a typo in the category line:
`Category = none`
should be
`category = none`
Not sure if this has any consequences in stock play, but when using FilterExtensions it causes these parts to appear under Fuel Tanks (in addition to the Life Support category.)

**Comment by LouisB3** [comment]
Also reported on the forums [here](http://forum.kerbalspaceprogram.com/index.php?/topic/105202-12-usi-life-support-050/&do=findComment&comment=2845082)

Workaround [here](http://forum.kerbalspaceprogram.com/index.php?/topic/105202-12-usi-life-support-050/&do=findComment&comment=2846613)

**Comment by BobPalmer** [comment]
Sorted in next release
