### ISSUE TITLE
Habitation Multipliers not being applied in VAB and SPH LS calculator

### ISSUE THREAD

**Issue by GHRyanK** [BobPalmer/USI-LS#160]
The habitation multipliers are not being accounted for in the VAB and SPH life support calculator.  Tried this with PPD-12, Viewing/Observation Cupolas, and both Tundra Kerbitats in Hab-Common config.  The multipliers do kick-in when the habs are activated on the pad.  Not a game breaker, but makes the design process VERY inefficient when trying to account for partial crew coverage by a hab part.

Also, a minor but recurring UI issue from previous update is hab time calculations in VAB will not update when crew count is changed unless a new part is added (any type of part, not just a hab one), or one is removed and re-attached.

Currently running KSP 1.2.1.1604 (edit: x64 version) with USI-LS 0.5.5.0 and MKS 0.50.5.0 (edit: plus latest Karibou and Survivability Pack).

**Comment by Tsaven** [comment]
Adding to this that I have the exact same problem.  See attached screenshot.
![screenshot0](https://cloud.githubusercontent.com/assets/19253861/20459388/7b2ebf94-af24-11e6-9006-f41880de1035.png)
