### ISSUE TITLE
Recycling does not count for inactive ships

### ISSUE THREAD

**Issue by nbspjr** [BobPalmer/USI-LS#161]
Steps:
1.  Launch a ship with some supplies, recycler, one kerbal and enough power/batteries
2. Enable recycler, check life support window (for me it shows consumption 2.3 supplies/day VS 10.8 supplies/day without recyclers)
3. Switch to another vessel/KSC and warp. I warped 26 days
4. Switch back to ship and check supplies.

Expected: 2.3*26=59.8 supplies used
Result: 281 supplies used. 281/26=10.8 (as if recyclers were off)

It works as expected if you don't switch vessels, i.e. if you just warp 26 days without unloading this ship, kerbal will eat ~59 supplies (2.3/day).

Saves attached (Ship name: LifeSupportAlpha-DEMO):
test-launch: on launchpad
test-orbit: ship is in Kerbin orbit
test-result: in orbit after 26 days

I have few mods installed, most of them are visual enchantments and additional features like KAC, KER, Chatterer, KIS, Docking indicator etc. And:

USI Life Support
USI Tools
USI Freight
Konstruction
Planetary Base System

[USI-Recyclers-Bug.zip](https://github.com/BobPalmer/USI-LS/files/599831/USI-Recyclers-Bug.zip)

**Comment by jd284** [comment]
May be the same bug as [MKS #1013](https://github.com/BobPalmer/MKS/issues/1013)

**Comment by BobPalmer** [comment]
This has been fixed
