### ISSUE TITLE
Agriculture module load not being maintained

### ISSUE THREAD

**Issue by GHRyanK** [BobPalmer/USI-LS#164]
The Ranger Agriculture module is not retaining load state for agroponics operations when coming in from a time-stopped state.  Specifically, the Agroponics field shows "zero efficiency" when coming into the game from a freshly launched vessel (out of the VAB).  Doing a quick-save, then re-loading that save evidently forces it to check state, as the field jumps to the expected load percentage for consumption after a few seconds.  I have not checked this with the other ag modules or different ag configs, nor while time warping from the Space Center view.  This might be related to USI-LS issue #161.

I'm currently running KSP 1.2.1.1604 (x64) with USI-LS 0.5.5.0, MKS 0.50.6, and latest Karibou and Survivability packs.

**Comment by BobPalmer** [comment]
Did a lot of bug fixes... after today's patch (1/2/17) please let me know if this persists.
