### ISSUE TITLE
When decoupling a lander and going outside the range of hab, lander crew refuses to work

### ISSUE THREAD

**Issue by DaymareDev** [BobPalmer/USI-LS#165]
Looks like it might be calculating remaining time from launch time instead of decoupling time.

**Comment by BobPalmer** [comment]
Need a save attached.

**Comment by DaymareDev** [comment]
Will quicksaves do, or do you need a zip? Here's a link: https://1drv.ms/f/s!AmnDNoFubCp6iOldnDS0SEayDMgQmw 
FYI: I'm a C# dev, so let me know if you want me to look at anything specific.

**Comment by DaymareDev** [comment]
@BobPalmer @SirBriguy  Hey guys, I am kind of put off KSP at the moment due to this issue. Can't really do any missions outside kerbin without removing LS. I am considering debugging this myself, any idea where to start?

**Comment by SirBriguy** [comment]
I usually start by putting prints in the code that calculates the values for the hab etc. Check out FixedUpdate::FixedUpdate and the functions it calls and work backwards.

**Comment by BobPalmer** [comment]
Fixed in the next patch
