### ISSUE TITLE
Missing textures and modules errors in the logs

### ISSUE THREAD

**Issue by ihsoft** [BobPalmer/USI-LS#166]
Textures:
```
161123T193742.362 [ERROR] [PartReader.ReadTextures] Texture 'UmbraSpaceIndustries/LifeSupport/Assets/NomTank_N' not found!
161123T193742.375 [ERROR] [PartReader.ReadTextures] Texture 'UmbraSpaceIndustries/LifeSupport/Assets/NomTank_N' not found!
161123T193742.379 [ERROR] [PartReader.ReadTextures] Texture 'UmbraSpaceIndustries/LifeSupport/Assets/NomTank_N' not found!
```
Modules (a lot of such records on game load):
```
161123T193810.561 [ERROR] [Part.AddModule] Cannot find a PartModule of typename 'ModuleConnectedLivingSpace'
```

Installed USI mods:
* USI Core
* USI Kolonization Systems (MKS/OKS)
* USI Life Support
* USI Tools

**Comment by okozlovsky** [comment]
Also:

> Texture load error in 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\UmbraSpaceIndustries\LifeSupport\Supplies.dds'

> d3d: failed to create 2D texture id=6197 w=18 h=18 mips=5 d3dfmt=894720068 [invalid call]
d3d: failed to create 2D texture id=1948 w=22 h=92 mips=7 d3dfmt=827611204 [invalid call]
d3d: failed to create 2D texture id=6333 w=18 h=18 mips=5 d3dfmt=894720068 [invalid call]
[TR.Loader] Generated mipmaps & compressed UmbraSpaceIndustries/LifeSupport/Supplies [36x36 DXT5 -> DXT5]

**Comment by BobPalmer** [comment]
textures sorted
