### ISSUE TITLE
USI-LS Incompatible with parts with staging actions

### ISSUE THREAD

**Issue by shadowmage45** [BobPalmer/USI-LS#17]
Due to a bug?/issues in BaseConverter that result in it calling part.force_activate(), activating all staging icons for that part.

This causes issues with non-stock command pods that include parachutes, decouplers, retro/launch escape engines... or anything with a staging icon.

A proposed solution can be found at:
https://github.com/shadowmage45/USI-LS/blob/master/Source/LifeSupport/LifeSupportConverter.cs
and
https://github.com/shadowmage45/USI-LS/blob/master/Source/LifeSupport/ModuleLifeSupport.cs

This solution works by replacing the inheritance chain of the life support module, replacing the problematic BaseConverter class with a custom/optimized converter that only includes the delta-time conversion updating stuff that is necessary for life support.

If this solution is deemed to be adequate, please let me know and I'll set up a proper fork and PR.

**Comment by BobPalmer** [comment]
Fixed in next patch

**Comment by shadowmage45** [comment]
Awesome, thanks much :)
