### ISSUE TITLE
Rebalance NOM's conversions

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/USI-LS#174]
NOM 5000:
* Inputs
  Mulch: 0.00012
  Fertilizer: 0.000012
  EC: 0.26
* Output
  Supplies: 0.000132

This conversion isn't enough to feed even one Kerbal. It's needed to have 4,1 NOM 5000s to feed one Kerbal. It would be nice if this was more straightforward to give at least 0,0005 Supplies as output and make it easier to understand what you are getting from these "recyclers".

It would be so much easier to use and understand if one NOM 5000 could feed one Kerbal and NOM 25000 could feed 5 Kerbals. Please reconsider this balance, because even if the user use a NOM 25000 it can only feed 2,4 Kerbals, it's too little.

**Comment by jd284** [comment]
Realistically speaking such a small greenhouse on its own shouldn't be able to support one Kerbal. However if you have a 70%+ recycler in addition to it (such as another Nom 5000 configured as recycler), it's enough to keep a Kerbal alive for a very long time (or as long as your fertilizer lasts anyway).

So I don't think it needs rebalancing really. Just don't try to use it without a recycler.

**Comment by BobPalmer** [comment]
Correct, this is by design
