### ISSUE TITLE
Parts with recycler load > 100% can make supply consumption zero or negative

### ISSUE THREAD

**Issue by jd284** [BobPalmer/USI-LS#176]
Parts such as the MKS Tundra Pioneer, where the recycler load is not a flat 100%, can make the supply consumption zero or negative when used in combination with other recyclers.
When supply consumption is negative, the info window displays "Expired" for supplies.

To reproduce, build a base with 5 kerbals (with 1 two-star engineer) and
- Stock MPL
- RT-5000 recycler
- Tundra Pioneer

When all three recyclers are enabled, and the Tundra load is ~142%, the supply consumption drops to zero, and above 142% it goes negative. Playing with how much machinery is on the part allows fine-tuning this.

So somehow the load also affects the recycling percentage? Not sure what the real bug here is, that the load can even be >100%, or that the load affects the percentage.

**Comment by BobPalmer** [comment]
This should be sorted
