### ISSUE TITLE
Kerbitat always counted as recycler in VAB

### ISSUE THREAD

**Issue by platonicsolidsa** [BobPalmer/USI-LS#180]
In the Life Support panel in the VAB, the Kerbitat is always counted as a recycler, even when it's set to a different config (ie: Hab Common).

For an example, this three-man ship shows a 1y 305d supplies endurance with the Kerbitat as a recycler, and it's indeed in recycler mode.

http://images.akamai.steamusercontent.com/ugc/106228751903491129/8FD0D7A2C1F5897A5FE2DCF1005EF4C2F9596168/

If I switch the Kerbitat to Hab-Common, it now get counted for habitation, but it's still showing up as a recycler and boost supply duration.

http://images.akamai.steamusercontent.com/ugc/106228751903491568/4899878D488438AE343F466D4498C185FBFCF3F0/

Once I get ot the pad, my actual supply endurance drops because there's no recycler and no way to turn one on.

http://images.akamai.steamusercontent.com/ugc/106228751903491801/57B6708CC3C2EF9FCD50CD069FC75C8AC650D980/

The same behavior happens on both the 2.5m and the 3.75m Kerbitats.

**Comment by BobPalmer** [comment]
Fixed next patch
