### ISSUE TITLE
Deployable Emergency Shelter Hab Time Not Properly Calculated

### ISSUE THREAD

**Issue by dboi88** [BobPalmer/USI-LS#182]
Bonus issue: Kerbitat recycler makes supplies go expired when turned on.

Emergency Shelter:
go to the craft on the runway and and open the life support gui, the minmus base has 165 days
warp until 1 day hab and home time left
now switch to the minmus base and the hab/home timer will now jump to 32 days

Kerbitat Recycler:
go to the minmus base, it has 223 days of supplies
turn on the kerbitat recycler and we have 2y 74 days
time warp and the supplies timer will slowly climb to 100y of supplies and then switch to expired there's still a few thousand supplies left at this point
the switch seems to coincide with the mulch tank filling up, but removing the mulch doesn't change anything

https://drive.google.com/file/d/0B_nRjcqonDoUMXhvcmU2SFA2YkE/view?usp=sharing

**Comment by BobPalmer** [comment]
Did a lot of bug fixes... after today's patch (1/2/17) please let me know if this persists.
