### ISSUE TITLE
Recycler parts completely unbalanced for size

### ISSUE THREAD

**Issue by cherrydev** [BobPalmer/USI-LS#186]
The large recycler can manage 80% for 3 Kerbals, which works out to 60% for 4 Kerbals. The small recycler can manage 60% for 1 Kerbal, so 4 small recyclers is functionally equivalent to 1 large one. However, the large recycler weighs 37x as much as a small one, consumes 37x as much power and costs 50x as much. This is according to the values in the VAB window. This matches with the numbers coming up in the Life Support Status window too. Did a decimal place get dropped here? If one were to assume that one large item would be somewhat more efficient (for power and mass) than a bunch of small ones, the large recycler would completely make sense if it supported 30 kerbals instead of 3 giving it a total efficiency slightly better than the small recyclers. On the other hand, the large recycler pretty much matches the capabilities of the Duna Kerbitat, so maybe the small ones are the ones that are improperly balanced.

**Comment by BobPalmer** [comment]
This is by design.  The key is that 80% capability.  The mass/volume of recyclers goes up dramatically as you cross to greater and greater recycle percentages.  So if you are fine with a low recycling value, it's better to have lots of low efficiency ones.  But what you really want is to get your recycling cap up, so it's also fine to use a mix of a smaller number of high efficiency recyclers with a bunch of small 'pre-filters' to optimize weight.

**Comment by cherrydev** [comment]
I get what you're saying, 80% recycling actually doubles the life support time over the 60% ones, but at a 1.8 ton premium per kerbal (it supports 3), and each unit of fertilizer being equivalent to 10 units of supplies…
Okay, so assuming you're getting all your supplies from fertilizer, it looks like the break-even point, compared to the small recyclers, just for weight, for saving on fertilizer would be 416.7 days, if I did the math right. Is this about what you intended?

**Comment by BobPalmer** [comment]
I have a huge spreadsheet somewhere that covers all of this... but short version is that it is as designed :)

**Comment by cherrydev** [comment]
Great, thanks for explaining it!
