### ISSUE TITLE
15-day supply grace period not applied if supplies run out while craft is unfocused

### ISSUE THREAD

**Issue by Wyzard256** [BobPalmer/USI-LS#187]
When a spacecraft runs out of supplies, it has a grace period (configurable, default 15 days) before the kerbals refuse to work.  But if it's not the active ship when the supplies run out, the grace period isn't applied.

Here's [a save](https://github.com/BobPalmer/USI-LS/files/659482/supply-bug.zip) that illustrates the issue.  There's one spacecraft in orbit, with about 33 days remaining on the kerbals' supply timers — that represents about 18 days of actual supplies, plus 15 days of grace period.

In the tracking station, open the Life Support Status window, then timewarp until the ship's remaining supplies reach zero and the kerbals' "sup:" timers reach 15 days.  When that happens, the supply timers drop instantly from 15 days to "expired".  Double-click the ship to open it, and the kerbals refuse to work; the supply timers remain expired in the flight scene.

If the ship is open (e.g. in the flight scene or orbit map) when the supplies run out, it behaves as expected: the supply timers turn yellow and continue to count down from 15 days.

**Comment by BobPalmer** [comment]
Patched in next update
