### ISSUE TITLE
Habitation and physics bubble issues

### ISSUE THREAD

**Issue by jd284** [BobPalmer/USI-LS#188]
Reporting from [this post](http://forum.kerbalspaceprogram.com/index.php?/topic/72032-12-usi-kolonization-systems-mksoks-0500/&do=findComment&comment=2895637) and the following.

Issue: Habitation of disconnected bases breaks when leaving the physics bubble of the main base and only aux bases without their own hab facilities remain in the bubble briefly.

Setup:
1 main base in the middle with all recyclers and hab facilities
2 aux bases (e.g. drilling rigs that require an engineer) less than 150m to the east and west of the main base, with no life support facilities of their own, just a single one-person pod for the engineer

To reproduce:
Launch a shuttle into orbit, or land near the base from orbit, and watch what happens when leaving/entering the physics bubble of the main base.

Details:
This setup works well while stationary with the main hab extending to both aux base. However, when a shuttle departs for orbit (i.e. towards the east), the main base leaves the shuttle's physics bubble first, and the eastern aux base is now alone with no hab or recycling. This causes the engineer to go on strike, or to die if configured that way.

Similarly, when landing from orbit (i.e. from the west of the base), the western rig enters physics range first, again with no hab or recycling facilities, so the engineer goes on strike or dies from lack of hab. If not set to KIA, at least he recovers quickly when when main base comes into range.

A solution could be to maybe stop life support processing when one component in a range of nearby 150m vessels gets unloaded, or to cache its properties and use the cache while processing the remaining bases.

**Comment by BobPalmer** [comment]
There's a potential fix for this in the next update - ping me if it does not fix it.
