### ISSUE TITLE
Allow locking supplies again, or make supplies follow flow priority rules

### ISSUE THREAD

**Issue by jd284** [BobPalmer/USI-LS#191]
Currently (in response to #33), it's impossible to lock supplies. I understand the reasoning behind this to make it impossible to intentional starve the crew, but currently this is excessively restrictive.

There are several reasons where locking some (but not all) supplies containers can be useful, or controlling the flow via flow priority settings:
- with multiple docked craft, control which supplies should get consumed first
- control where locally produced supplies should be stored
- interaction with planetary logistics (MKS)

For instance, I have a relatively large moon base, with several Karibou parts as well as greenhouse parts. These all have fairly large supplies storage (3300 in total for me), but aren't warehouse parts, so the supplies stored there do not participate in planetary logistics. So there's no way of setting it up such that the produced supplies end up only in the MKS ISM that can push them to planetary storage. In other words, until I have produced 2475 supplies to fill up the (otherwise useless) non-warehouse storage, nothing ends up in planetary logistics.

So please either make it possible to lock supplies again, or make supplies (both production and consumption) follow flow priority so that I can control where they should go first.

**Comment by BobPalmer** [comment]
This has changed in the next release.  Kerbals will unlock containers when they cannot find any unlocked supplies.
