### ISSUE TITLE
Incorrect habitation value and blank setup/vab screen.

### ISSUE THREAD

**Issue by archnem** [BobPalmer/USI-LS#192]
Setup screen is blank when starting a game.  VAB screen is blank unless I detach/reattach a part.  Habitation multiplier is calculated incorrectly after ship is launched or reverted or parts are added/removed in VAB.

[SaveAndLog.zip](https://github.com/BobPalmer/USI-LS/files/684058/SaveAndLog.zip)

**Comment by BobPalmer** [comment]
Need specificity on the 'calculate incorrectly' part.  And I cannot repro a blank screen in the VAB (unless it is a new ship... at which point, it is normal for it to be blank until there's a part on the vessel.

**Comment by archnem** [comment]
Alright.  I've put together an imgur album showing exactly what I'm doing and the results:

http://imgur.com/a/VI95i

I mention this in the album, but the bug seems centered around certain parts - the Tundra modules seem to work fine.  Please take a look when you can.  I'm also downloading KSP onto my girlfriend's machine to see if I can replicate the issue under a different hardware setup.  I have both a Win10 and Linux Mint partition on my machine, and get this behavior on both OSs.  Thanks for your time.

**Comment by archnem** [comment]
I just put a fresh install on my gf's machine and am having the exact same issues there.  It's actually kind of a relief that it's not machine-specific lol.  Just FYI, her specs:

Intel i3-3225 @ 3.3Ghz
8GB RAM
Intel HD 4000 GFX
Win10 Home 64-bit

**Comment by archnem** [comment]
I've been doing my own rudimentary troubleshooting on this today.  I've now replicated this behavior across 4 machines and 5 different OSs.  I've tried everything I can think of short of cloning your repo and recompiling from source (mainly because I don't know jack about unity lol).  I've included a few new screenshots here

[newscreens.zip](https://github.com/BobPalmer/USI-LS/files/688541/newscreens.zip)

In the first one, you can see I've built a simple ship, and the hab multiplier is being calculated correctly as 1+4.45, and shows that with a full crew, I should be getting 1y:302d of hab time.
I then launch the ship and start all the habs, but the monitor only shows 296d of hab time! Oh noes!
I revert to the VAB and now the multiplier shows as 1+1.22...which gives the 296 days.

I've deleted and reinstalled the game, gotten a completely different copy from someone in case my particular steam install was borked, put KSP and USI on a few different machines, I even reformatted my drive and reinstalled Windows, all to no avail.  And guessing by the "wow, that's just weird" reaction I got in the USI-LS thread, apparently your mods just hate me, personally.  I don't know what I ever did, I've only ever had nice things to say about them :)  The only point of commonality I can figure between all the systems is that they're all Intel processors. *shrug*

Anyhow, if you ever do have a chance to look at this or figure this out, it'd be awesome, but I'm guessing this is some weirdness that only I am a party to, so probably not a priority.  I am giving up and just turning hab off, which sucks, I like the mechanic.  I've been getting weird bugs with supply timers in previous versions as well, but haven't tried the newest release, so fingers crossed, hopefully they're not an issue anymore (as I'd much rather use USI than TAC with MKS).

Anyhow, thanks for your time and your awesome mods.

**Comment by BobPalmer** [comment]
Opened the attached save, and I have no issues - can't repro.  Which tells me there's something else going on that I am not aware of.
