### ISSUE TITLE
Fertilizer with same mass of supplies

### ISSUE THREAD

**Issue by NyankoSensei** [BobPalmer/USI-LS#20]
Fertilizer is useless becouse have the same mass of supplies,  and by the code 
	MODULE
	{
		name = ModuleResourceConverter
		tag = Agroponics
		ConverterName = Agroponics
		StartActionName = Start Agroponics
		StopActionName = Stop Agroponics
		INPUT_RESOURCE
		{
			ResourceName = Mulch
			Ratio =  0.0002
		}
		INPUT_RESOURCE
		{
			ResourceName = Fertilizer
			Ratio =  0.00004

		}
		OUTPUT_RESOURCE
		{
			ResourceName = Supplies
			Ratio = 0.00024
			DumpExcess = False
		}
		INPUT_RESOURCE
		{
			ResourceName = ElectricCharge
			Ratio = 12
		}
	}
is more easy transport supplies than fertilizer

**Comment by BobPalmer** [comment]
Incorrect.

The normal converter is lossy - you can convert mulch to supplies, but you lose some of the mulch.  The fertilizer conversion is lossless, so it has a significant advantage.

**Comment by NyankoSensei** [comment]
You are right, sorry for my bad interpretation and thanks for all your great mods
