### ISSUE TITLE
Crew Number in planner not updating when changing crew

### ISSUE THREAD

**Issue by dboi88** [BobPalmer/USI-LS#202]
[From](http://forum.kerbalspaceprogram.com/index.php?/topic/105202-12-usi-life-support-050/&do=findComment&comment=2919485) Forum user [Garwel](http://forum.kerbalspaceprogram.com/index.php?/profile/141813-garwel/)
"It looks like a bug in Life Support Status window in the VAB. I loaded a vessel with 2 kerbals, then removed one, opened the LS Status window, but it still showed "Current (2)"."

![image](https://cloud.githubusercontent.com/assets/5978114/21908053/23734800-d90a-11e6-8726-c124de212824.png)

**Comment by BobPalmer** [comment]
Fixed next patch
