### ISSUE TITLE
Infinite NullReferenceException in VAB

### ISSUE THREAD

**Issue by agustincaniglia** [BobPalmer/USI-LS#203]
The last version of Usi-LS 0.5.16.0 throws constant "NullReferenceException: Object reference not set to an instance of an object" red messages into the log as soon as you put colonization module at the lab. This does not happen with previous version 0.5.15.0 and different versions (including all latests) of dependencies were tested, not only by me, but also by dboi88 who confirmed this in the USI-ls Thread. This problem is serious because it kills the framerate as the log files is loading several mb of information constantly expanding the size to big numbers rapidly, not stopping.
(Side note: This is my first github activity, forgive me if I've made something not properly, but I haven't had a proper response yet on the thread, so I took care of delivering this info to here.)

**Comment by BobPalmer** [comment]
Fixed in next patch

**Comment by agustincaniglia** [comment]
No it's not fixed in the last version 0.5.18.0

**Comment by BobPalmer** [comment]
Fixed for real in next patch
