### ISSUE TITLE
Recyclers don't work while vessel is unfocused

### ISSUE THREAD

**Issue by TinoR242** [BobPalmer/USI-LS#208]
It seems that during catch up recyclers aren't taken into account.

1. Basically I put 3 kerbals, 500 supplies and 3 recyclers into orbit, when I start the recyclers the supplies countdown increases to 53 days, as expected.
![imagen](https://cloud.githubusercontent.com/assets/25176524/22024830/9cfa01f4-dccb-11e6-8ec1-f69ca01533df.png)

2. Then I time warp in the tracking station for 5 days: 48 days of supplies left.
![imagen](https://cloud.githubusercontent.com/assets/25176524/22024852/ada0b070-dccb-11e6-8942-bc899df869e3.png)

3. But when I get back to the vessel, there are only 41 days of supplies left and 162 supplies were consumed, the exact amount for 3 kerbals during 5 days and no recyclers working.
![imagen](https://cloud.githubusercontent.com/assets/25176524/22024871/bb5fe47e-dccb-11e6-9356-13682df78ed5.png)

This save file has step 1 done, 3 kerbals in orbit with the recyclers already started.
[Recyclers_1.zip](https://github.com/BobPalmer/USI-LS/files/711352/Recyclers_1.zip)

This save file has step 2 done, time warp for 5 days.
[Recyclers_2.zip](https://github.com/BobPalmer/USI-LS/files/711353/Recyclers_2.zip)

I think this could be related with this other issue: #204

**Comment by jd284** [comment]
This bug is still present in 0.5.20 (with USITools 0.8.11).
During catchup, the recycler says "Life Support: Operational", instead of the normal "Life Support: 100%".

**Comment by BobPalmer** [comment]
Sorted next release
