### ISSUE TITLE
Refuses to work spam and exception when info window is displayed during flight

### ISSUE THREAD

**Issue by jd284** [BobPalmer/USI-LS#212]
I get the following exception once every second while the info window is open, when there are other occupied vessels in the area. Note that there are no EVAs so I'm not sure what's going on. This is also accompanied by spam of "X refuses to work" (with no reason so apparently it's from ApplyEVAEffect even though there's no EVA), followed right away with "X has returned to duty" and brief flicker of the window. This happens for the first kerbal in all vessels except the focused one.
Unfortunately I'm playing RSS so I can't provide a USI-only save.

```
[LOG 18:16:32.960] Applying EVA Effect
[LOG 18:16:32.961] Applying EVA Effect
[EXC 18:16:32.961] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
        System.Collections.Generic.List`1[ProtoCrewMember].get_Item (Int32 index)
        LifeSupport.LifeSupportMonitor.CheckEVAKerbals ()
        LifeSupport.LifeSupportMonitor.GenerateWindow ()
        LifeSupport.LifeSupportMonitor.OnWindow (Int32 windowId)
        UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
        UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```

**Comment by Gnurfos** [comment]
I see 3 problems with method CheckEVAKerbals():

1. It is doing `var c = v.GetVesselCrew()[0];` which will produce the exception quoted above, when the vessel is unmanned
2. It is checking: `if(v.isEVA)  continue;` but I think the intent should be `if(!v.isEVA) continue` , as it follows by assuming the vessel is an EVA kerbal. This will lead to taking the vessel (spaceship)'s mission time and compare it to the allowed EVA duration, triggering false positives EVA expiries
3. The most important point to me: it has side effects, whereas in my opinion all these should be constrained into some of the other classes that already modify life support status. The monitor window should only read/display things.

**Comment by Gnurfos** [comment]
I pushed more stuff in [PR213](https://github.com/BobPalmer/USI-LS/pull/213) that should fix all 3 points. I'm not sure of the actual effects thought (they shouldn't be different from when it was checked in the monitor and working, but I don't know what turning an EVA Kerbal into a tourist could do for example).

**Comment by BobPalmer** [comment]
This PR has been merged and will be in the next patch
