### ISSUE TITLE
Crew Becoming Tourists After Landing

### ISSUE THREAD

**Issue by Pakes** [BobPalmer/USI-LS#219]
Ok, this is a weird one.
I am using a lot of mods but I am quite sure that this bug is a LS issue. After Getting habitat/home starved kerbals from a spacestation and taking them home on a probe vessel, they become tourists.

In depth description: Had 4 kerbals on a station near minmus, 2 of them habitat/home starved in a lab (KSP interstellar mod lab). After picking them up and landing on kerbin only the 2 previously habitat starved kerbals became tourists (even if the probe I used had no life support and all the 4 of them starved in the journey from station to kerbin).

**Comment by BobPalmer** [comment]
Need a save file (with just USI/Stock mods) to investigate.
