### ISSUE TITLE
[Bug] Incorrect Hab-time calculations in the VAB

### ISSUE THREAD

**Issue by Terwin1** [BobPalmer/USI-LS#224]
USI only deployment on 1.2.2 with Tools: 8.15, Core 3.8, MKS 50.16, LS 5.22

 Way-station with 2 of 34 kerbals in VAB:  (Hab-time for 34 kerbals listed as 4y:91d)

http://imgur.com/bnlCqU2

Way-station with 22 of 34 kerbals in VAB: (Hab-time for 34 kerbals listed as 416d)

http://imgur.com/V6KbqGP 

(The album has similar images from my current game, including one on the Mun with LS and all hab parts open to show they are active.)

Craft file:
[Mun Way-station.craft.txt](https://github.com/BobPalmer/USI-LS/files/785144/Mun.Way-station.craft.txt)

**Comment by Terwin1** [comment]
PolecatEZ mentioned in the forums that Supplies are often affected similarly

**Comment by BobPalmer** [comment]
Looks to be sorted in the next release

**Comment by Terwin1** [comment]
I just checked this on version 0.6.0
The Supplies calculation looks like it it fixed, but the hab time calculation for the max number of kerbals still changes every time I add or remove a kerbal from the vessel(unless I am switching between 0 and 1 kerbal)
