### ISSUE TITLE
Community Tech Tree config for USILS_LgRecycler (and Nom-O-Matics)

### ISSUE THREAD

**Issue by erebus42** [BobPalmer/USI-LS#229]
Currently the large recycler is in Survivability, and the small one is in Recycling.
Not sure if its an omission or by design, but I'm suspecting you need to add this to CTT.cfg 
Edit: (Actually it looks like it was in commit ccaf363b55ab2ac97e31f20205ed33d3140a5fe9, but its not in 0.5.23 release).

@PART[USILS_LgRecycler]:NEEDS[CommunityTechTree]
{
    @TechRequired = recycling
}

Also I'm not sure if the Nom-O-Matics need to be moved to Hydroponics, but that's what I've done for my games.

@PART[USILS_Greenhouse_MiniCupola]:NEEDS[CommunityTechTree]
{
    @TechRequired = hydroponics
}
@PART[USILS_Greenhouse_Inline]:NEEDS[CommunityTechTree]
{
    @TechRequired = hydroponics
}
@PART[USILS_Greenhouse_Cupola]:NEEDS[CommunityTechTree]
{
    @TechRequired = hydroponics
}

The cupola seems out of place there too, but I don't know where would be the best place to put it.

**Comment by Merkov** [comment]
I'm not sure if you saw or not, but I re-submitted this as a new pull request (#234). Hopefully it will fix things at the next release. Does it look good to you?

**Comment by BobPalmer** [comment]
Closing this as it should be fixed next release - if not, re-send the PR
