### ISSUE TITLE
ModuleLifeSupportSystem.Start is never called

### ISSUE THREAD

**Issue by jd284** [BobPalmer/USI-LS#230]
VesselModule.Start is a non-virtual function and so the ModuleLifeSupportSystem.Start never gets called.
It should probably override the OnStart method instead, using "protected override void OnStart()". Probably this would also allow/require the commented OnDestroy code to work again.

It seems because of this the vessel is never set dirty? 

Not making a PR yet because I'm not sure if Start should be fixed like this, or the dirty checking removed (since currently it is without function anyway).

**Comment by BobPalmer** [comment]
Sorted this - thanks!
