### ISSUE TITLE
Vessel LastFeeding set to zero when loading with no supplies / LS monitor prematurely displays "expired"

### ISSUE THREAD

**Issue by jd284** [BobPalmer/USI-LS#231]
When a savegame is loaded when a vessel's supplies have run out, somehow the vessel's LastFeeding time is set to zero. This causes the LS monitor to display "expired" even when still within the grace period (the kerbal's timers are still valid).

Steps to reproduce:

1. Load a vessel with supplies about to run out, or have a vessel where supplies ran out while it wasn't focused and hasn't been focused since
2. Wait until supplies have run out. Notice monitor correctly displays "starving" and the remaining time
3. Quicksave, check savegame: LastFeeding time is correct
4. Quickload, notice monitor now displays "expired"
5. Quicksave again: LastFeeding time is now zero

There's probably be the same issue with EC time.

**Comment by BobPalmer** [comment]
This is fixed in the next release
