### ISSUE TITLE
USI-LS is not removing recovered/deleted/destroyed vessels

### ISSUE THREAD

**Issue by JPLRepo** [BobPalmer/USI-LS#29]
I've noticed in the persistence file that USI-LS is not removing recovered/deleted/destroyed vessels.
The VESSEL_DATA config nodes just keep growing and old vessels persist/are not being removed.
The same goes for the STATUS_DATA config nodes for the kerbals.

**Comment by Wercho** [comment]
This also applies to ships that are renamed. The old names don't get cleaned out, so you end up with entries for each name a ship had.

**Comment by BobPalmer** [comment]
This should be resolved in the next release
