### ISSUE TITLE
Request: Small Part included that converts mulch -> supplies

### ISSUE THREAD

**Issue by DanPli** [BobPalmer/USI-LS#3]
Please consider adding a small part that converts mulch into supplies into the Lifesupport pack for those who cannot install the whole MKS/OKS system. It should preferrably be green and blue, looking really shiny and expensive, be massless, dragless, and be able to hold an ample amount of mulch, monopropellant and uh...

...ok, or it just converts mulch. Regardless of how it looks.  

:D

**Comment by BobPalmer** [comment]
greenhouse was added previously
