### ISSUE TITLE
Kerbals forget that they are starving if they go below 50km without landing.

### ISSUE THREAD

**Issue by gregbean** [BobPalmer/USI-LS#32]
If starving kerbals pass below 50km on Kerbin (for instance, during aerobraking), their 'hunger timers' are reset due to the no-starving-below-50km clause.  However, once their trajectory takes them back above 50km, their starvation counter starts again from scratch - they've forgotten that up until sixty seconds ago, they were starving and grouchy.  This allows one to 'break the strike' and get kerbals back to work without feeding them.

**Comment by BobPalmer** [comment]
By design ;)
