### ISSUE TITLE
Kerbals raid non-locked supplies regularly

### ISSUE THREAD

**Issue by NatTuck** [BobPalmer/USI-LS#33]
I get the "[name] has raided the supplies, some fell out the airlock" frequently even when there are plenty of supplies.

This happens
 1.) When time-warping.
 2.) When switching to a vessel that's been unfocused long enough to run down some container of supplies, but before agroponics production has time to catch up.

**Comment by BobPalmer** [comment]
The supply raiding mechanic has been replaced with auto-unlocking of containers in the next release.
