### ISSUE TITLE
Kerbals in an external command seat don't consume supplies

### ISSUE THREAD

**Issue by swilbur** [BobPalmer/USI-LS#35]
If a kerbal is in an external command seat, it will not consume any supplies.  I'm pretty sure this is because the 'crew' is stored on the KerbalEVA part rather than the Seat part, and I don't think it's possible for ModuleManager to edit the KerbalEVA part to add a ModuleLifeSupport.

**Comment by BobPalmer** [comment]
This should be corrected in the next release
