### ISSUE TITLE
Kerbals remain tourists

### ISSUE THREAD

**Issue by MynarMoonshadow** [BobPalmer/USI-LS#39]
Non Orange suit kerbals never revert to their original professions after becoming tourists.  It seems the first kerbal to grab the supplies and throw the rest out of the airlock is the only one that does not change to a tourist.  After returning to Kerbin and landing, the message says they have returned to work but still remain tourists in the astronaut complex and upon exit KSP and restarting.  More details in USI-LS thread.

**Comment by BobPalmer** [comment]
Thanks - the single kerbal grabbing supplies is the intent, but should work on successive kerbals.  Fixing in next update.
