### ISSUE TITLE
Crew refusing to work on pad

### ISSUE THREAD

**Issue by linuxgurugamer** [BobPalmer/USI-LS#45]
I just had a problem where crew was refusing to work on the launchpad.  Adding some LS supplies fixed the problem.  However, I recruited a new pilot and she was willing to work.
This happened right after I upgraded (via CKAN) to 0.2.0.0

**Comment by linuxgurugamer** [comment]
I found and added some more detail (duplicated on the forum):

More details:  The crew who was refusing to work was Jebedia and Valentina, both of whom had several missions under their belts.  Neselle was a new pilot I recruited

I wonder if the mod isn't resetting the time since their last meal?

I just looked in the save file, and I'm guessing that's the problem.  Here is the status data, when no one is in space.  Neselle was the kerbal I recruited, notice the last meal values:

        LIFE_SUPPORT_SETTINGS
        {
            STATUS_DATA
            {
                KerbalName = Jebediah Kerman
                LastMeal = 2797139.62094199
                IsGrouchy = False
                OldTrait = Pilot
                LastUpdate = 2797139.62094199
            }
            STATUS_DATA
            {
                KerbalName = Valentina Kerman
                LastMeal = 2420403.18696142
                IsGrouchy = False
                OldTrait = Pilot
                LastUpdate = 2420403.18696142
            }
            STATUS_DATA
            {
                KerbalName = Neselle Kerman
                LastMeal = 3832232.72435278
                IsGrouchy = False
                OldTrait = Pilot
                LastUpdate = 3832300.04435284
            
 On a side note, would you prefer my NOT posting in both places?  I'm posting here for you to track, and on the forum for others to learn from.  Whichever you prefer is fine, just let me know.

**Comment by blandau** [comment]
This is also happening to me in space when I go EVA. When Jeb or Val hop out of the vessel, I get the message "refuses to work." If I hop back in, they still refuse. It was my understanding that the orange suits don't need supplies.

If I include supplies on the vessel, then everyone, including Jeb and Val, are happy.

My suspicion is that this is related to going EVA. If I don't go EVA, then Jeb and Val keep working.

**Comment by linuxgurugamer** [comment]
@blandau 

Make sure you have the updated settings file, there are new changes which I don't see in what you posted above

**Comment by blandau** [comment]
@linuxgurugamer 

This is the settings.cfg file under GameData\UmbraSpaceIndustries\LifeSupport. My USI-LS.version file, in the same folder, says it is 0.2.0.0.

**Comment by BobPalmer** [comment]
Fixed in the new release
