### ISSUE TITLE
LS Status Window only displaying crew for current vessel

### ISSUE THREAD

**Issue by Blu3wolf** [BobPalmer/USI-LS#46]
What it says on the label. After updating, I only can see the supply status of my current vessel, although I have several concurrently with crew.

**Comment by BobPalmer** [comment]
Should be sorted, be sure to revisit your ship

**Comment by Blu3wolf** [comment]
Hi! 

I've just finished writing an article and I wanted to  ask you to take a look at it aand tell me  your opinion about it, please read  the whole article here <http://grant.psphacking101.com/e7oik/92>

Yours truly, blue
