### ISSUE TITLE
Mass of Nom 5k

### ISSUE THREAD

**Issue by mhoram-kerbin** [BobPalmer/USI-LS#48]
Regarding #31 I find it a bit confusing that
https://github.com/BobPalmer/USI-LS/blob/master/GameData/UmbraSpaceIndustries/LifeSupport/Parts/Greenhouse.cfg
has a mass of 0.55 ton while
https://github.com/BobPalmer/USI-LS/blob/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/LifeSupport/Parts/Greenhouse.cfg
has a mass of 1.5 ton.
Shall I make a PR to adjust the mass of the second one to 0.55 ton?

**Comment by BobPalmer** [comment]
Corrected in next release
