### ISSUE TITLE
VAB USI-LS window causes main USI-LS window reset

### ISSUE THREAD

**Issue by Kowgan** [BobPalmer/USI-LS#59]
Opening the USI window inside the VAB causes all the current vessels on the main list to disappear. Cross-posted from the forums:

If I launch a vessel from the VAB without ever opening the VAB USI-LS window, everything works fine:
http://puu.sh/mIKq7/f1ecef2288.jpg

But once I open the USI window while at the VAB , the bug happens.
http://puu.sh/mIKXO/89054dcb14.jpg
http://puu.sh/mIKN1/b1d00d7e88.jpg

**Comment by fat-lobyte** [comment]
I can confirm that this bug still exists in version 0.3.8.

**Comment by BobPalmer** [comment]
Fixed in next release
