### ISSUE TITLE
life support display nonsensical for ships with no kerbals on board.

### ISSUE THREAD

**Issue by billkerbinsky** [BobPalmer/USI-LS#6]
The life support status display is somewhat confusing for craft which have supplies but no kerbals on board - it looks nearly the same as a craft with kerbals with no supplies, looking like something that needs attention.  (Maybe this only happens if there are also empty seats on board).

Might make more sense to show the total supplies on board in kerbal-days or kerbal-years.

**Comment by Saelack** [comment]
Second the confusion - but think there possibly needs to be a "filter" option - I only want to see Ships, with Kerbals onboard, in orbit around the Mun.

Might be over doing it, but would sure help trimming down the list.  :)

**Comment by KraigL** [comment]
Agree with filter option suggestion.  The Rescue Kerbal missions now also spawn a craft which ends up on the Life Support display forever (with 0 crew).  

I have been renaming these "wreakage crafts" as debris when the rescued Kerbal leaves.  However, they are still displayed with red stats and 0 crew, even when classified as debris (and filtered from game display).

**Comment by tivec** [comment]
I second this, I have vessels with -121 days of supplies, but it has never had a single Kerbal on board.
