### ISSUE TITLE
"Everyone has wandered back to the KSC"

### ISSUE THREAD

**Issue by jamieT06** [BobPalmer/USI-LS#62]
So it was my understanding that people would just become tourist if starved except orange suits. Decide to pack all my kerbals into a ship and get a lot of experience, taking four tourist with me. Landed on mun and minmus on the way back to Kerbin, swtch back for final approach and everyone, orange suits and all passengers, have somehow managed to get back to the KSC from low kerbin orbit with reset experience. 
Which kinda sucks

**Comment by BobPalmer** [comment]
Changed in a recent release per the thread.  You can always tweak the configs back down if so inclined.
