### ISSUE TITLE
Recyclers in the Mobile Processing Lab have no effect

### ISSUE THREAD

**Issue by fat-lobyte** [BobPalmer/USI-LS#66]
The "Start life support" button in the right-click menu of the Mobile Processing Lab is not functional.

The only thing that changes is that the supply time left is shown (incorrectly), but this time goes down multiple seconds per seconds.

Observe the Supply left time according to USI on the left, and according to Alternate Ressource Panel on the right.

Turned off: 277 days, according to USI tab, and according to Alternate Ressource panel
http://i.imgur.com/5gg4W4m.jpg

Turned on:  2y 75 days according to USI tab, and 277 days according to Alternate Ressource panel
http://i.imgur.com/VrHcJpF.jpg

I am using Version: 0.3.8

**Comment by BobPalmer** [comment]
Unfortunately I have no idea how ARP is calculating this...  Is there some other evidence that can be shown?

**Comment by BobPalmer** [comment]
Either way, tested the old fashioned way with a notepad and timewarp.  Fixed in next release.
