### ISSUE TITLE
Orbital bases showing up as "Landed".

### ISSUE THREAD

**Issue by apocriva** [BobPalmer/USI-LS#68]
When viewing the Life Support Status window, orbital bases show up as "Landed".
![usils_issue00](https://cloud.githubusercontent.com/assets/12013168/12869833/e5da5102-cd00-11e5-8865-24849883872b.PNG)

**Comment by apocriva** [comment]
I'm currently on USI-LS 0.3.9.

**Comment by Kowgan** [comment]
Can confirm. This has been happening since .0.3.6.

**Comment by BobPalmer** [comment]
This should be sorted in the next patch.
