### ISSUE TITLE
Change labeling for Habitation

### ISSUE THREAD

**Issue by mcortez** [BobPalmer/USI-LS#70]
First I'm very tempted to ask that you tweak the terminology of using "hab" values for two different things, 1) how long before a vessel stops contributing to habitation, or becomes uninhabitable and 2) how long a particular kerbal is willing to "habitate" away from home.

Personally, I think habitation (Hab) for the vessel and home sickness (HS) for the other would be best -- and visiting a station with a high habitation value makes you willing to stay away from home longer.  Checking out a nice vista while on EVA would also make you forget about home for a while -- now you just need to figure out how to detect things like eclipses -- EVA during eclipse + 30 days before HS.

**Comment by BobPalmer** [comment]
Labels have been adjusted in the next patch
