### ISSUE TITLE
Habitation time Readout incorrect if Recyclers are enabled

### ISSUE THREAD

**Issue by fat-lobyte** [BobPalmer/USI-LS#72]
Please consider the following two pictures:

http://imgur.com/a/FDVEK

Here you see, that in the 10 seconds that have passed between the screenshots, the remaining habitation time has gone down by 31 seconds.

It seems that when the Recyclers are enabled, they produce "Wear" (consume ReplacementParts), that reduces the vessels maximum habitation time which in turn reduces the kerbals current habitation time, faster than the game time.

I'm not sure if the Wear produced by the Recyclers is a feature (why would recycling cause wear on the parts?).

Either way, the habitation time readout should show the actual time that the Kerbal has currently left, not "a time if no recyclers were running". This should also be reflected in the VAB in order to reduce surprises.

**Comment by BobPalmer** [comment]
How many recyclers are on that vessel and turned on?

**Comment by akors** [comment]
Only one, it's the MPL recycler.

**Comment by fat-lobyte** [comment]
Only one, it's the MPL recycler.
