### ISSUE TITLE
Supplies always empty after long periods of unfocused timewarping

### ISSUE THREAD

**Issue by fat-lobyte** [BobPalmer/USI-LS#73]
Hi! So I have found a somewhat difficult issue, with USI-LS 0.3.11

1. Create a craft with Kerbals, an MPL, a Nom-o-Matic 5000, batteries & solar panels.
2. Remove some Supplies, add some Mulch, leave Fertilizer full
3. Launch the craft, start the Agroponics module
4. Observe that the supplies go up over time, as well as the Life support time in the USI-LS window. This holds up even under timewarp

5. Go to the space center, timewarp a certain amount of time (let's say the time it takes until the supplies container is full)
6. Go back to the vessel, open the ressource panel *instantly*!
7. Observe that in the beginning, the supplies are full, but within several seconds they become depleted
8. Observe that the net output is still positive, and if you keep the vessel focused, supplies replenish over time

So it seems that the catch-up mechanic of the Agroponics converter fills up the supplies storage first, only THEN does the Kerbal Supplies consumption happen - which obviously leaves an empty supplies tank.

To solve the bug, one should either somehow "interleave" the consumption/production or create an unconstrained buffer for the output, subtract the consumption and then clip the the buffer to the maximum storage capacity of the vessel.

**Comment by gregbean** [comment]
I have also seen this behavior.  Details of my experiments are:

Given a mun base containing:

    200 days of supplies
    room for 200 days worth of mulch
    200 days worth of fertilizer
    a nom-o-matic 25000
    a 2m reactor sufficient to power the nom-o-matic 25000
    four kerbals

I observe:

While focused, the nom-o-matic is able to outpace the kerbals' production of mulch. Mulch drops to 0 and stays there as the nom-o-matic consumes all available mulch.

I would expect, when returning to this base after a long time away, that I would see mulch stay near zero and fertilizer drop as the nom-o-match catches up.

However, if I return to the KSC, warp 100 days, then return to the base, I observe:

    over the course of the first minute, life-support consumption 'catches up' - lots of supplies are consumed and lots of mulch is produced very fast.
    almost no fertilizer is consumed.
    mulch fills up to half (100 days' worth)

After the 'catch up' completes, mulch and fertilizer begin dropping again, and supplies begin to climb again, at their normal rates. If I timewarp while focused on the base, mulch again returns to 0.

It does not appear that the nom-o-matic is catching up alongside the supply consumption when the base is being loaded after a time away.

versions:

USI-LS: 0.3.11.0
UKS: 0.33.6
USI Tools: 0.6.2.0

**Comment by BobPalmer** [comment]
The likely cause of this is that multiple iterations of ModuleLifeSupport are running in a given tick.  So more 'time' is given to them.  Granted, everything catches up once you're finished up, but for the first bits, life support definitely takes a bit of precedence.

**Comment by BobPalmer** [comment]
Actually... scratch that.  Think I found the issue.

**Comment by BobPalmer** [comment]
This has been corrected for the next release.
