### ISSUE TITLE
nom-o-matic doesn't 'catch up' after long periods unloaded

### ISSUE THREAD

**Issue by gregbean** [BobPalmer/USI-LS#75]
Given a mun base containing:

- 200 days of supplies
- room for 200 days worth of mulch
- 200 days worth of fertilizer
- a nom-o-matic 25000
- a 2m reactor sufficient to power the nom-o-matic 25000
- four kerbals

I observe:

While focused, the nom-o-matic is able to outpace the kerbals' production of mulch.  Mulch drops to 0 and stays there as the nom-o-matic consumes all available mulch.

I would expect, when returning to this base after a long time away, that I would see mulch stay near zero and fertilizer drop as the nom-o-match catches up.

However, if I return to the KSC, warp 100 days, then return to the base, I observe:

- over the course of the first minute, life-support consumption 'catches up' - lots of supplies are consumed and lots of mulch is produced very fast.
- almost no fertilizer is consumed.
- mulch fills up to half (100 days' worth)

After the 'catch up' completes, mulch and fertilizer begin dropping again, and supplies begin to climb again, at their normal rates.  If I timewarp while focused on the base, mulch again returns to 0.

It does not appear that the nom-o-matic is catching up alongside the supply consumption when the base is being loaded after a time away.

versions:

USI-LS: 0.3.11.0
UKS: 0.33.6
USI Tools: 0.6.2.0

**Comment by fat-lobyte** [comment]
#73 is a duplicate of this issue, I suggest closing yours to prevent confusion.

**Comment by gregbean** [comment]
Closing as duplicate of 73.
