### ISSUE TITLE
HabMultiplier and BaseHabTime default to 1

### ISSUE THREAD

**Issue by jr05** [BobPalmer/USI-LS#77]
I noticed that changing HabMultiplier and BaseHabTime in the settings file didn't seem to affect the habitation values in game.  I may be misreading the code, but I think what is happening is that finalSettings initializes with both these values set to 1.  Since the code that reads the settings looks for a minimum, its not actually possible to set the HabMultiplier or BaseHabTime to a value greater than 1.

**Comment by BobPalmer** [comment]
Fixed in next release
