### ISSUE TITLE
ModuleLifeSupportRecycler minor addon Request

### ISSUE THREAD

**Issue by gandi3k** [BobPalmer/USI-LS#79]
Is it possible to add KSPfield for dump DumpExcess = False/true?

I am trying to make it compatible with TAC, and there are three Ressources for life Support. And if Water is full. They dont recycle any Food or Oxygen. (because Water iss full)

Thanks for reading.

**Comment by BobPalmer** [comment]
It's a standard generator, so that would already exist.
