### ISSUE TITLE
Vessels left unattended by kerbals for periods of time will consume supplies when a kerbal enters the vessel for the period it was empty.

### ISSUE THREAD

**Issue by JPLRepo** [BobPalmer/USI-LS#86]
I got a bug reported for DeepFreeze and it appears they are correct. With the latest version of USI LS my DeepFreeze mod is no longer working with USI LS.
hen a kerbal is frozen using DeepFreeze I was calling LifeSupportManager.UntrackKerbal method to remove them from USI LS which was handling the situation correctly.
With the latest version of USI LS the call to UntrackKerbal is still functioning... but when they are thawed USI LS picks them up as crew again and then begins consuming all the resources for the period of time they were frozen. Any clues what you have changed to cause this? Otherwise I will have to go on a code review and debugging spree.
Thanks.

OK an update. I did a bunch of testing and debugging (couldn't help myself).
It appears to be a bug in USI LS for any vessel that is Empty for a period of time....
When a kerbal boards the vessel they consume resources like crazy. I believe it begins in the ModuleLifeSupport partmodule FixedUpdate. The first line checks if there are no kerbals on board then it does nothing.
Because of this GetDeltaTime is not called and lastUpdateTime is not updated.
So when a kerbal eventually does board the vessel it starts calling GetDeltaTime and tells the ResourceConverter to start processing the recipe. 
I note in the GenerateLSRecipe it factors in numCrew (number of crew on board the part), but it isn't process thanks to that check at the start of FixedUpdate. I'm assuming this check is there just for performance reasons.
So I conducted a test :- Removed the Crew check (first line) of FixedUpdate and placed a CrewCount > 0 check from where it starts looking at the Hab info in FixedUpdate. Seems to have fixed this problem for both when a vessel is left un-kerbal'd or in my case where all the crew are frozen for a period of time.
I sent you a PR on GitHub.
Updated Pull Request to DEVELOP  Branch.
https://github.com/BobPalmer/USI-LS/pull/87

**Comment by BobPalmer** [comment]
Thanks, merged!
