### ISSUE TITLE
Supply Recipe runs at max DeltaTime warp until caught up to current time on returning to Vessel.

### ISSUE THREAD

**Issue by bennord** [BobPalmer/USI-LS#88]
Let's say you have a vessel with a:
75% recycler 
Agroponics - AgModule

So that your supplies are sustained as long as you have Fertilizer.
You warp at full speed for a year in the Space Center.
Then come back to your vessel.

Supply->Mulch will start happening as if you are at full warp still. ~4 per tick, instead of the nice ~4 per day.  The Agroponics can't keep up, so the supply is all consumed.

Seems like the issue could be in the way DeltaTime is updated here:

```C#
        protected double GetDeltaTime()
        {
            if (Time.timeSinceLevelLoad < 1.0f || !FlightGlobals.ready)
            {
                return -1;
            }

            if (Math.Abs(lastUpdateTime) < ResourceUtilities.FLOAT_TOLERANCE)
            {
                // Just started running
                lastUpdateTime = Planetarium.GetUniversalTime();
                return -1;
            }

            double deltaTime = Math.Min(Planetarium.GetUniversalTime() - lastUpdateTime,
                ResourceUtilities.GetMaxDeltaTime());
            lastUpdateTime += deltaTime;
            return deltaTime;
        }
```

Specifically the lines at the end, which update lastUpdateTime by GetMaxDeltaTime on each FixedUpdate call.

Or, maybe something else is happening, but there's definitely something out of whack...

**Comment by fat-lobyte** [comment]
To some extent, this is "on purpose". What happens is that the kerbals consumption catches up.

There are some other problems with this approach though, noted here: #73 .

**Comment by bennord** [comment]
Ok, if this is the same issue, then this might be a dupe of #73 .  

If it is the case that the current design plays "catch up" with only the supply consumption part of the equation, then that could be the cause of the bug.  

Since that recipe is E/C + supplies ==> mulch, then any parts producing supplies or producing E/C would need to play "catch up" in the same manner to keep things working correctly.

**Comment by bennord** [comment]
Actually, since other resources could involved in the "supply" loop, like a part that mines for water to produce supplies, E/C used by the parts, etc... it might be required (and simpler) to do ALL ship processes in step until they are caught up.  If that is the approach that is taken...

**Comment by BobPalmer** [comment]
FYI, all of this should be on precisely the same timer (i.e. the life support loop is kicking in at the same rate as the loop used for generators, etc.).

**Comment by BobPalmer** [comment]
This has been corrected for the next release.
