### ISSUE TITLE
Switching seats in docked vessels causes duplicate consumption of supplies

### ISSUE THREAD

**Issue by fat-lobyte** [BobPalmer/USI-LS#89]
Hi,

it seems that some very funky business is going on when vessels are docked,undocked, and seats are switched.

  1. Launch the following vessel, with one Kerbal in it.
  http://i.imgur.com/uTjrMqg.png

  It consists of:
    - Life Support Tank 1.25
    - RTG
    - Mk1 Lander Can
    - 4x RCS Thruster Block
    - Probodobodyne OKTO
    - Docking Port
    - Docking Port
    - Mk1 Lander Can
    - 4x RCS Thruster Block
    - RTG
  Note that this vessel has supplies for 30 days.

  2. Decouple Node between the two docking ports
  3. Re-dock the two vessels
  4. Go back to the space center, timewarp 15 days
  5. Go to the vessel. Observe that 15 days worth of supplies are correctly deducted
  6. Transfer the Kerbal from one Pod to the other, internally (without EVA)
  7. Observe that *another* 15 days worth of supplies are deducted.

**Comment by BobPalmer** [comment]
See if this persists after the next update.

**Comment by fat-lobyte** [comment]
Yep, this is definitely fixed :) Thanks for the patches!
