### ISSUE TITLE
Undocking resets 15 day timer on unsupplied vessels

### ISSUE THREAD

**Issue by jr05** [BobPalmer/USI-LS#92]
Undocking still resets the unsupplied timers for the crew of the unfocused vessel.  It does not seem to affect the hab timers after your most recent changes, but docking appears to reset the hab timers for both crews now.  The fact that the hab and supply timers are behaving somewhat differently suggests that it's not a full reset like it was before.

**Comment by jr05** [comment]
I tested this a little more.  The supply timer is resetting on the unfocused vessel when undocking, but only the short term hab timer is resetting when docking.  I think the hab timers are working as intended, so the bug is just the supply timers on undocking.

**Comment by BobPalmer** [comment]
Fixed in the next release
