### ISSUE TITLE
Values in Editor Part Menu

### ISSUE THREAD

**Issue by jofwu** [BobPalmer/USI-LS#93]
The "output" values for the MPL Recycler are missing. Also, it would be nice if we could get Habitation "extra time" and "multiplier" values shown for parts that have those. 

![screenshot39](https://cloud.githubusercontent.com/assets/8247331/13534554/b94ae012-e203-11e5-9eea-0f684f794d39.png)

**Comment by jofwu** [comment]
I wasn't thinking clearly when I posted this, considering there are no outputs. So I assume that field is blank on purpose.

That said, it would be nice if we could get the recycler efficiency listed somewhere. (along with the Hab info mentioned)

**Comment by BobPalmer** [comment]
Now in tooltips
